{"homepages":[],"source_base_path":"E:/documents/Petrik/documents/software/nuclei/nuclei.exceptionhandling/doc/Nuclei.ExceptionHandling.Documentation","xrefmap":"xrefmap.yml","files":[{"type":"Conceptual","source_relative_path":"index.md","output":{".html":{"relative_path":"index.html","hash":"wGLb3+W5IaK86gnZXQBR9g=="}}},{"type":"Toc","source_relative_path":"obj/api/toc.yml","output":{".html":{"relative_path":"api/toc.html","hash":"OLB/yxn4/WfyQ8KmTMImqg=="}}},{"type":"Toc","source_relative_path":"toc.yml","output":{".html":{"relative_path":"toc.html","hash":"ciE4Dt1DZX2463ewNeaAZw=="}}},{"type":"Conceptual","source_relative_path":"api/index.md","output":{".html":{"relative_path":"api/index.html","hash":"FikFN2eH9iocdmfu8BHFQQ=="}}},{"type":"ManagedReference","source_relative_path":"obj/api/Nuclei.ExceptionHandling.ExceptionProcessor.yml","output":{".html":{"relative_path":"api/Nuclei.ExceptionHandling.ExceptionProcessor.html","hash":"rRaZfXhdZ7fc7lRyxAef9g=="}}},{"type":"ManagedReference","source_relative_path":"obj/api/Nuclei.ExceptionHandling.yml","output":{".html":{"relative_path":"api/Nuclei.ExceptionHandling.html","hash":"wJEBvSkTEs/BZ8Wcyvn0nQ=="}}},{"type":"ManagedReference","source_relative_path":"obj/api/Nuclei.ExceptionHandling.ExceptionHandler.yml","output":{".html":{"relative_path":"api/Nuclei.ExceptionHandling.ExceptionHandler.html","hash":"ZmZAFo8J1mOiZ+q53Esvzw=="}}}]}